# Generated by Django 4.2 on 2024-10-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('unique_id', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('url', models.CharField(blank=True, max_length=1024)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('big_metadata', models.JSONField(blank=True, null=True)),
                ('secret_value', models.JSONField(blank=True, null=True)),
                ('followers', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_id', models.CharField(max_length=1024)),
                ('url', models.CharField(blank=True, max_length=1024)),
                ('title', models.TextField(blank=True)),
                ('like_count', models.BigIntegerField(blank=True, default=0)),
                ('comment_count', models.BigIntegerField(blank=True, default=0)),
                ('view_count', models.BigIntegerField(blank=True, default=0)),
                ('share_count', models.BigIntegerField(blank=True, default=0)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('big_metadata', models.JSONField(blank=True, null=True)),
                ('secret_value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='chickenapi__name_a44905_idx'),
        ),
        migrations.AddField(
            model_name='contenttag',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_tags', to='chickenapi.content'),
        ),
        migrations.AddField(
            model_name='contenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_tags', to='chickenapi.tag'),
        ),
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chickenapi.author'),
        ),
        migrations.AddIndex(
            model_name='contenttag',
            index=models.Index(fields=['content'], name='chickenapi__content_886eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='contenttag',
            index=models.Index(fields=['tag'], name='chickenapi__tag_id_d02e42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contenttag',
            unique_together={('content', 'tag')},
        ),
    ]
